# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$all'
right_format = '$status$cmd_duration'
# Inserts a blank line between shell prompts
add_newline = false


[character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
success_symbol = '[\[I\]](bold green)'
error_symbol = '[\[I\]](bold red)'
vimcmd_symbol = '[\[N\]](bold green)'
vimcmd_replace_one_symbol = '[\[R\]](bold blue)'
vimcmd_replace_symbol = '[\[R\]](bold purple)'
vimcmd_visual_symbol = '[\[V\]](bold purple)'

[cmd_duration]
# format = 'took [$duration]($style)'
format = '[$duration]($style)'
style = 'dimmed bright-white'

[directory]
fish_style_pwd_dir_length = 1
home_symbol = '~'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
# symbol = ' '
# symbol = '󰊢 '
symbol = ''
style = 'bold green'

[git_commit]
only_detached = true

[git_metrics]
disabled = true

[git_status]
style = 'bold yellow'
format = '([$conflicted$ahead_behind$stashed$deleted$renamed$modified$typechanged$staged$untracked]($style) )'

conflicted = '[= ](bold red)'
ahead = '⇡$count '
behind = '[⇣ ](bold red)'
diverged = '[⇕ ](bold red)'
stashed = '\$ '
modified = '!$count '
untracked = '[?$count](bold blue)'
staged = '+$count '
renamed = ''
deleted = ''

[lua]
# symbol = ' '

[package]
disabled = true

[status]
disabled = false
symbol = '✘'

##  format = '$all'  is equivalent to (no blank lines, I added them :P) :
# format = """
# $username\
# $hostname\
# $localip\
# $shlvl\
# $singularity\
# $kubernetes\
# $directory\
# $vcsh\
# $fossil_branch\
# $fossil_metrics\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $hg_branch\
# $hg_state\
# $pijul_channel\
# $docker_context\
# $package\
### Languages and stuff here
# $buf\
# $nix_shell\
# $conda\
# $meson\
# $spack\

# $memory_usage\

# $aws\
# $gcloud\
# $openstack\
# $azure\

# $nats\
# $direnv\
# $env_var\
# $mise\
# $crystal\
# $custom\
# $sudo\
# $cmd_duration\

# $line_break\

# $jobs\
# $battery\
# $time\
# $status\
# $os\
# $container\
# $netns\
# $shell\
# $character"""



## For defining custom colors and stuff:
# palette = 'foo' # Probably should define it but idk
#
# [palette.foo]
# # Overwrite existing color
# blue = '21'
# # Define new color
# mustard = '#af8700'
